### ISSUE TITLE
Consider adding explicit HTTPS timeout (say, 1m?)

### ISSUE THREAD

**Issue by danmarg** [mrisher/smtp-sts#104]
As discussed here: https://mailarchive.ietf.org/arch/msg/uta/nim_1MlGLEtU66EVguMwvjtTFKY

**Comment by mrisher** [comment]
Feels like 60 seconds is good enough; will wait for UTA to weigh in otherwise we'll do that.

**Comment by jjones425** [comment]
Agree with 60 seconds, give UTA until next week to respond and then update / close.

**Comment by jjones425** [comment]
Replied back to Ned's email asking him if he had specific feedback for this issue as he replied to the UTA thread with general feedback, creating a new issue to track Ned's feedback.

**Comment by jjones425** [comment]
Replied back to Viktor's email, asked him to comment on Dan's suggestion to get this issue closed out.

**Comment by abrotman** [comment]
Did we decide not to do this?

**Comment by danmarg** [comment]
d214801
