### ISSUE TITLE
Specify that 'enforce' also reports in the 'Policy Application' section?

### ISSUE THREAD

**Issue by lbaudoin** [mrisher/smtp-sts#109]
When a policy fails and the mode is 'enforce' it seems that we should report the failure as well as fail. 
An alternative is to have an 'enforce and report' mode.

**Comment by mrisher** [comment]
Wouldn't this return `sts-invalid` in the TLSRPT report? Or is there another place you'd like to report this?

**Comment by lbaudoin** [comment]
Without also reading the TLSRPT RFC it wasn't clear that the STS 'enforce' mode would also report so it might help to mention it in the STS document. It is not a big deal I just thought I'd mention it.

**Comment by danmarg** [comment]
d6019c5
