### ISSUE TITLE
SMTP TLS Reporting does not specify retry for HTTPS POST rua

### ISSUE THREAD

**Issue by eyeofthenico** [mrisher/smtp-sts#112]
While SMTP reporting would benefit from softfail retries, the HTTPS POST webhook does not specify retry behavior.
In order to have some reliability, I think we suggest policy like exponential backoff and suggest a minimal number of retries.

**Comment by abrotman** [comment]
I mostly agree, though I'd probably just say that if it can't be delivered within 24hrs, drop the report.  I guess I feel like if a receiver hasn't noticed that they aren't getting reports from anyone after 24hrs, they're probably not doing much with them anyway.

**Comment by abrotman** [comment]
https://github.com/mrisher/smtp-sts/blob/abrotman_1/mta-sts.md

**Comment by danmarg** [comment]
This was merged in, right? Reopen if I'm mistaken.
