### ISSUE TITLE
TLSRPT: Success count should indicate what kind of authentication was used

### ISSUE THREAD

**Issue by danmarg** [mrisher/smtp-sts#117]
It seems to me that instead of just a "success count", we should have something like:

starttls-successes
mta-sts-successes
tlsa-successes

or similar. Otherwise, how is a recipient to know how many senders actually validated the cert or enforced encryption?

**Comment by abrotman** [comment]
Could that not be gleaned from the policy stanza?  I can't imagine a sender would include a policy they don't intend to validate.  I don't mind splitting it out, but I wonder if it is necessary.

**Comment by abrotman** [comment]
Okay, I think Dan and I are in agreement, going to close this
