### ISSUE TITLE
"A lenient parser SHOULD" is unclear

### ISSUE THREAD

**Issue by davidillsley** [mrisher/smtp-sts#131]
The current draft states
> A lenient parser SHOULD accept TXT records and policy files which are syntactically valid (i.e. valid key-value pairs separated by semi-colons for TXT records and valid JSON for policy files) and implementing a superset of this specification, in which case unknown fields SHALL be ignored.

I think this is suggesting that all parsers should be lenient in this way, but the english is ambiguous, and may suggest that if you're not implementing a `lenient parser`, it doesn't apply.

It would be clearer if it were something like

> Parsers SHOULD accept TXT records and policy files which are syntactically valid (i.e. valid key-value pairs separated by semi-colons for TXT records and valid JSON for policy files) and implementing a superset of this specification, in which case unknown fields SHALL be ignored.

**Comment by danmarg** [comment]
55fc0de

**Comment by danmarg** [comment]
(In branch minor-edits. Will merge in after someone reads it.)
