### ISSUE TITLE
Provide an example of a subdomain Policy Domain

### ISSUE THREAD

**Issue by davidillsley** [mrisher/smtp-sts#132]
The definition of Policy Domain is currently:

> Policy Domain: The domain for which an STS Policy is defined.
      (For example, when sending mail to "alice@example.com", the policy
      domain is "example.com".)

It may not be clear what the Policy Domain is for a subdomain eg david@uk.example.com or manager@hr.example.com. Given that DMARC supports policy inheritance and SPF doesn't, being clear for a new email specification would be helpful.

**Comment by danmarg** [comment]
b20b31b
