### ISSUE TITLE
Section 5, 5.2 and Appendix 2 seem to conflict

### ISSUE THREAD

**Issue by davidillsley** [mrisher/smtp-sts#133]
Section 5 states:
> "enforce": In this mode, sending MTAs treat STS policy failures
       as a mail delivery error, and MUST NOT deliver the message to
       this host.

Section 5.2 states:
> If no candidate MXs are valid and the policy mode is "enforce",
       temporarily fail the message.  (Otherwise, generate a failure
       report but deliver as though MTA STS were not implemented.)

Section 5.2 seems to allow the message to be sent when the policy is violated, which doesn't seem likely to be the desired behaviour. Is the "Otherwise" statement supposed to only apply to sending the generated report? If so, this text could be omitted as it's more clearly specified in the reporting spec:
> When sending failure reports via SMTP, sending MTAs MUST NOT honor SMTP STS or DANE TLSA failures.

This confusion seems to be reflected in Appendix 2, which seems to allow a message to be sent insecurely in response to any set of errors, which again conflicts with Section 5, and the stated purpose in the introduction:
> what a conforming client should do with messages when TLS cannot
      be successfully negotiated

**Comment by danmarg** [comment]
The "otherwise" refers to the mode being "report", which I think clears this up. I will change the text to reflect this.

**Comment by danmarg** [comment]
c710ac12bc2a678ffd8a9b908b02b9f2e35cacaf
