### ISSUE TITLE
Revert the _txt -> txt record rename

### ISSUE THREAD

**Issue by danmarg** [mrisher/smtp-sts#134]
In the case of mta-sts, it prevents the use of CNAMEs where the TXT has the same record name. D'oh.

**Comment by abrotman** [comment]
damned if we do, damned if we don't?

**Comment by mrisher** [comment]
Good catch. How annoying!

**Comment by danmarg** [comment]
I'm sure someone will mention the option to put the TXT record at the
top-level domain. I don't personally like that (detecting STS based on "v="
prefixes seems fugly to me), but we could do it.

**Comment by danmarg** [comment]
4d7ed1e..c10a389
