### ISSUE TITLE
Get the policy body out of the TXT record

### ISSUE THREAD

**Issue by mrisher** [mrisher/smtp-sts#14]
If policies were always validated by HTTPS (as described in issue #13 ), then we wouldn't need a policy in the TXT record at all--just a version indicator, to (ab)use DNS's caching and allow senders to cheaply detect when to look for a refreshed policy. This could be done by sticking any old string in the TXT record--a nonce, hash of the version, date string, monotonically-increased number, or whatever. (The sender need not care how this is generated; the sender should merely cache the policy _and_ version string, so as to detect when the version string has changed.)

This presents two advantages:

1. It simplifies deployment a little bit; policy domains can update the published policy via HTTPS and then flip the version string separately; at no point will senders see an invalid (i.e. mismatched between TXT and HTTPS) policy.

2. It simplifies hosted usage quite a bit. A mail hosting provider can also host an HTTPS endpoint that serves the most up-to-date policy (using SNI to sign with the customer's certificate), without needing to also put the policy in the customer's DNS zone. This means the host can update the policy at will without the customer needing to do more than increment the version.

**Comment by abrotman** [comment]
Would there be a benefit to requiring a timestamp string?  If that timestamp is newer than your most recent cached version of the HTTPS policy, you should re-fetch the policy.

**Comment by danmarg** [comment]
Well, you either store a timestamp or you store some other string. I'm not
sure it matters. The argument for timestamp is that if you're caching in
some form (memcache, flat files) that natively supports timestamps,
timestamps may be easier to compare. But storing an extra version string
per policy isn't a huge deal...

**Comment by mrisher** [comment]
Dan says Viktor says just use any string that, if it changes, means you need to refresh the policy.
