### ISSUE TITLE
Clarify the preferred order to update a policy

### ISSUE THREAD

**Issue by eriklax** [mrisher/smtp-sts#149]
In the "Policy Updates" section I can't see that the preferred order to update a policy is clearly defined. I believe that would be to first update the HTTPS endpoint, and then the TXT record in order to prevent senders to "accidentally" cache the old HTTPS policy again but the new TXT record's version id.

> Updating the policy requires that the owner make changes in two places: the _mta-sts TXT record in the Policy Domain's DNS zone and at the corresponding HTTPS endpoint. As a result, recipients should thus expect a policy will continue to be used by senders until both the HTTPS and TXT endpoints are updated and the TXT record's TTL has passed.

Reading the paragraph one could assume they should update the TXT record first since it's mentioned first.

**Comment by danmarg** [comment]
Good point. You are certainly understanding the issues correctly, but to make it more clear I agree we should suggest that people update the HTTPS policy first. See if the clarification in 3c5f53c makes sense; I can reword this if it's still unclear or confusing. :)
