### ISSUE TITLE
Harmonize with HSTS Directives (max-age and includeSubDomains)

### ISSUE THREAD

**Issue by mrisher** [mrisher/smtp-sts#16]
Suggestion was to ensure the SMTP STS (`SSTS`?) directives are consistent with HSTS ones. Cf. https://tools.ietf.org/html/rfc6797#section-6.1

**Comment by mrisher** [comment]
1. Change `e` parameter to `max-age` to match HSTS style
2. Create a table of the other directives (mx patterns, reporting destination, etc.) that match the HSTS style (CamelCase words instead of abbreviations)
3. Move that table into the "registry" that Chris Newman is working on for DEEP, so we can manage future extensibility

**Comment by abrotman** [comment]
I put the registry in the appendix for our reported items.  Did you also want a table of the policy attributes to be stored in this registry as well?  From reading what the intent was for the DEEP registry, it seemed more suited to the report items.  If this isn't quite what you were after, let me know.  I'll definitely have time Sunday evening to do anything else you're looking for.

**Comment by mrisher** [comment]
@abrotman, because a bunch of merges jumped in front of you, and because I changed the filename (from `spec.md` to `sts-mta.md`), I couldn't easily pull in your stuff automatically. I *think* this correctly covers it: can you please take a look and confirm?

https://github.com/mrisher/smtp-sts/commit/88f8903681ed2f689be1341da6d7b389052528e4

**Comment by mrisher** [comment]
fixed long ago by @abrotman
