### ISSUE TITLE
Use RFC 7405 case-sensitive ABNF

### ISSUE THREAD

**Issue by danmarg** [mrisher/smtp-sts#161]
e.g. std-version    = %s"v=STSv1"

**Comment by danmarg** [comment]
8059c9a
@prbinu @abrotman Either of you have time to double check this commit (even though I already made it)?

**Comment by abrotman** [comment]
Did you forget to define "sts-ext-value"?  I don't see it in the diff.  Otherwise, looks good. 


On Tuesday, August 1, 2017, 6:11:57 PM EDT, danmarg <notifications@github.com> wrote:


8059c9a
@prbinu @abrotman Either of you have time to double check this commit (even though I already made it)?

**Comment by danmarg** [comment]
Also 8e4cf4d..353a821

**Comment by danmarg** [comment]
Not in the diff, but it's in the draft:

~~~
    sts-extension   = sts-ext-name "=" sts-ext-value     ; name=value

    sts-ext-name    = (ALPHA / DIGIT) *31(ALPHA / DIGIT / "_" / "-" / ".")

    sts-ext-value   = 1*(%x21-3A / %x3C / %x3E-7E)       ; chars excluding
                                                         ; "=", ";", SP, and
                                                         ; control chars
~~~

There's an ABNF compiler somewhere I can use to generate representative input and ensure it compiles, so to speak. I didn't check it though.
