### ISSUE TITLE
Use case-sensitive ABNF in reporting

### ISSUE THREAD

**Issue by aykevl** [mrisher/smtp-sts#173]
See issue #161.
It's fixed for MTA-STS but not yet for SMTP-TLSRPT. Using RFC 7405 would make the ABNF a lot easier to read.

**Comment by danmarg** [comment]
I believe it is already in use. From draft 08:


     tlsrpt-subject = %s"Report" FWS               ; "Report"
                      %s"Domain:" FWS              ; "Domain:"
              domain-name FWS              ; per RFC6376
              %s"Submitter:" FWS           ; "Submitter:"
              domain-name FWS              ; per RFC6376
              %s"Report-ID:" FWS           ; "Report-ID:

The comments are admittedly not the most helpful now.
 
Did we miss some other place?

**Comment by danmarg** [comment]
Sorry, I see that in the TXT record this was not done. Done here: https://github.com/mrisher/smtp-sts/pull/180.

**Comment by aykevl** [comment]
Yes, thanks!
