### ISSUE TITLE
Create standalone specification for SMTP STS reporting

### ISSUE THREAD

**Issue by mrisher** [mrisher/smtp-sts#18]
And while we're under the hood, consider whether we should hew more closely to DMARC or another existing reporting format.

**Comment by danmarg** [comment]
Or HPKP's JSON...?

**Comment by abrotman** [comment]
I don't think we align closely enough to any existing report formats (that I'm aware of) that we could utilize them for STS as they are.  I think I'm more interested in JSON than XML, but honestly, either would work.

**Comment by mrisher** [comment]
fixed.
