### ISSUE TITLE
Sender domain in JSON report

### ISSUE THREAD

**Issue by aykevl** [mrisher/smtp-sts#187]
In the report there is an `organisation-name`, a `contact-info` and a `sending-mta-ip` but there is no field for the sender domain. The sender domain is listed in the attachment file name and in MIME headers, but depending on the transport and receiver these may be dropped (e.g. via HTTPS). I think it's useful for report processors to know the sending domain.
Also, it may be better to add some language that this sender must match the DKIM validated domain - currently the email MUST be validated using DKIM but isn't very clear which domain it should be signed with (the "reporting domain").

**Comment by abrotman** [comment]
What should we do in the case of something like Gmail who could be sending on behalf of numerous domains?

**Comment by aykevl** [comment]
I don't really know - a simple solution is requiring reports are sent per sending domain. Another could be making a list of the sending domains, but which domain should it be signed with then? All of them? It makes the report (and validating it!) more complex. And what about mail servers that send mail on behalf of *lots* of domains (e.g. Mailchimp)?
I'm just noticing that there appears to be no way to validate the DKIM signature which makes the signature rather useless. So of course another option is simply dropping the requirement for a DKIM signature. Being able to validate the sender would be nice, though it doesn't seem *that* important to me.

**Comment by danmarg** [comment]
Doesn't this mix two different "domains", though? The draft says the report must be signed by the reporting domain; it doesn't specify (as far as I can tell) that the reporting domain must be the same as the envelope or header From domain on the mail that the report is *about*, though I think that's the obvious use case. 

So there's no reason in principle that Mailchimp can't send a report with d=mailchimp.com containing data on failed sends from all their user domains, right?

**Comment by abrotman** [comment]
Would it be easier if instead of the 5321 domain, we instead used the same domain as is in the report (the domain from the contact-info) as the "sender" in the filename?  That would (I think) solve the issue of the DKIM signing, and also alleviate some confusion about the "sending domain".  

Considering the number of entities that send on behalf of other organizations (Gmail, 1&1, Comcast, Microsoft, etc.), this may make more sense.  I'm not going to contact alice@foo.org about TLS difficulties if her mail is handled by bob@bobtech.com.  And by putting the mail-management-domain into the report body, the filename, and the subject, this may make it easier to correlate and escalate.  

Thoughts?

**Comment by danmarg** [comment]
I think this makes sense, and it's less bothersome than dropping the DKIM MUST (though I agree with @aykevl that that's not maybe necessary, either; why would I spoof these reports anyway?).

**Comment by aykevl** [comment]
Yes, separating the From:/envelope-from domain from the reporting domain seems like a good idea. Especially as it is used in some locations that require a single domain (e.g. the filename). It might be a good idea to make this distinction clear in the spec, to avoid confusion (e.g. for report receivers that assume the reporting domain and the mail from domain are the same).

I'm not so sure about assuming the contact email has the same domain as the reporting domain - although it would make sense. Currently it can be any address.

It looks like we're now joining reports from different domains that use the same sending domain. I'm not sure whether this is entirely intentional. This also means the envelope from domain may not be clear anymore, and statistics are hard to calculate per from domain. This doesn't matter for security (the mail servers are the same and it's mostly about the envelope to domain) but means the statistics are mostly useless for other purposes. I can't really think of one but just mentioning it here just in case.

---

Off topic: I haven't gotten any report yet from Yahoo or Gmail. I'm wondering whether I have an invalid configuration or these reports simply haven't been implemented yet -- assuming the latter.

**Comment by danmarg** [comment]
I can't speak to Yahoo personally, but I don't believe Yahoo has yet
implemented this. Gmail has not. We're working on it. :)

**Comment by aykevl** [comment]
@danmarg thanks! It would help testing the spec I think.

**Comment by aykevl** [comment]
It looks like this is fixed.
