### ISSUE TITLE
Wildcards in MX constraint allow for DNS hijacking

### ISSUE THREAD

**Issue by mrisher** [mrisher/smtp-sts#20]
If the MX constraint has a wildcard (e.g. `e=*.mailhost.com`), then if an attacker can get a certificate for a subdomain of mailhost.com and can poison DNS, he can potentially intercept messages whenever he wants irrespective of policy lifespan.

Solution could be don't allow wildcards, but then we introduce a synchronization issue, where I have to update my policy before I can stand up a new MX. Doesn't seem that difficult at first blush, but it would probably require coordination between two teams.

**Comment by danmarg** [comment]
Seems to me this is more a caveat for policy authors, no? I think wildcard
is at least a useful option to have.

**Comment by abrotman** [comment]
I'd agree, I think this belongs in the Ops Guide.

**Comment by mrisher** [comment]
It's definitely useful, the concern was whether it encourages sloppy
behavior, and maybe we should be more prescriptive (in a self-documenting
way). Maybe we just specify if this an MSDOS wildcard or a regex (i.e. does
it expand to subdomains?)

**Comment by prbinu** [comment]
wildcard option is useful. I think we need more consistency there. For example when we say mx: *.example.com, is it just one level sub-domain (TLS cert's SAN model - eg. a.example.com) or is it a wild wildcard (eg. a.b.example.com). Following cert's SAN model would be more consistent.

**Comment by mrisher** [comment]
Agreed on consistency. There's a standard that seemed pertinent: "Checking
of Wildcard Certificates" rules in Section 6.4.3 of
<https://tools.ietf.org/html/rfc6125#section-6.4.3>RFC6125
<https://tools.ietf.org/html/rfc6125#section-6.4.3>. How does that compare
to the SAN model?

/m

.

**Comment by prbinu** [comment]
> How does that compare to the SAN model?
I was referring the same  ([https://tools.ietf.org/html/rfc6125#section-6.4.3])

**Comment by mrisher** [comment]
fixed with [RFC6125](https://tools.ietf.org/html/rfc6125#section-6.4.3)
