### ISSUE TITLE
Please clarify the term and procedure of "smart host"

### ISSUE THREAD

**Issue by bwurst** [mrisher/smtp-sts#201]
In section 3.4 you cover policy delegation to a "smart host". This term and the procedure is not clear to me. 
The term "smart host" is well known for outgoing mail servers (when the sender log in to send mail) but this seems not applicable here. The definition as "intermediate" does not help me any further. :)

What exacly is needed when a mail server operator receives mail for dozens of domain names? Is the classic MX record sufficient (is the domain name of the MX hostname used as policy domain?) or does one need to setup dozens of web server hosts with valid certificates and reverse-proxy?

**Comment by danmarg** [comment]
Why does it not seem applicable here? I think the meaning is exactly as you are familiar with: for cases where the sending MTA does not use the MTAs pointed to in the destination domain's MX record(s) but, instead, uses some other policy-configured MTAs that in turn relay to the ultimate destination MX, the sending MTA must validate any policy that exists for the policy-configured MTA, not the destination MXs. 

For example, if server A is configured to route all outgoing mail through server B, and A is sending to someone at domain C (via, of course, B), A should validate the policy for B when connecting to B, not the policy for C. 

However, to your second paragraph, you may be describing a scenario that is not "smart hosting": when some multi-tenant host like (say) Google GSuite hosts mail for a bunch of customer domains, the customer domain must in some manner (reverse proxy or not) serve policies for their domains with certificates matching their domains. The only way for senders to know the policy for "customer.com" is correct is to see it served with a "customer.com" cert, not a "host.com" cert. 

Does that answer your questions?

**Comment by bwurst** [comment]
Thank you for your reply. Yes, this answers my questions in a way that I now understand what you mean in the draft.
I couldn't imagine that you have a separate paragraph for smart hosts as smart hosts are typically used with login credentials (so TLS really should be set up) or within a trusted network where the use of TLS is up to the admin of the network. But okay, not a problem.

The second is the core of my question and I really think this will make a problem with deployment of SMTP-STS. We are a very small hosting provider and we operate a web and mail server for about 1000 domain names. So to get a complete SMTP-STS setup, we would need 1000 additional virtual hosts with 1000 TLS certificates or (when I correctly understand section 3.3) we could get a certificate with as many SANs as possible and configure vhosts with lots of aliases appropriately. 

The latter one is kind of hard to automate, the first is a huge waste of resources. On one hand, I can understand that it's not built on DNSSEC and you cannot trust your DNS, so delegation via simple DNS record would be insecure. But on the other hand, I hoped it could be more handy for this case.

**Comment by danmarg** [comment]
If you are operating a Web hosting service for 1k domains, aren't you likely to want to serve HTTPS for them (especially in light of [upcoming browser changes](http://www.zdnet.com/article/in-security-push-chrome-to-mark-all-http-pages-as-non-secure/))? 

Have you looked into automating this with Certbot and LetsEncrypt or similar? That should make this relatively painless for you, I hope.

**Comment by bwurst** [comment]
Well, we already do all this. 

But setting up the mta-sts hostname for all domains would nearly double the number of vhosts (and double config parsing time, cert loading time, used log file handles and all that stuff).
If you kind of deprecate DNSSEC by putting valuable information in HTTPS instead of DNS, I wonder why there's no generic DNS-replacement hostname like "_dns.domain.com" that can hold various information in one place. If you require a mta-sts-hostname, then someone else requires xmpp-sts or whatever in the future. I just think this may not scale. (And, to be realistic, most of those hostnames will not be accessed for years, I think.)

I'll follow the draft and the discussions and decide later what's the way to go.
