### ISSUE TITLE
Alexey: text/plain

### ISSUE THREAD

**Issue by abrotman** [mrisher/smtp-sts#209]
> 4) 3.2.  MTA-STS Policies
> 
>    The [RFC7231] "Content-Type" media type for this resource MUST be
>    "text/plain".
> 
> I think this requirement is a bit strong, because we should really
> register a new text/... media type for the policy format documented in
> the draft. I appreciate that this is not necessarily what you want to do
> in the document.

-We removed the above statement. Regarding the use of text/plain, It is not clear, what is the issue with -using text/plain content type. Is it not already registered Content-Type? (RFC1521)?

Nothing is wrong with using it. I am just thinking that if a more specific Content-type is registered for reports, it can be used that as well. So the MUST will prohibit that.

**Comment by prbinu** [comment]
I think no further action is required on this.
