### ISSUE TITLE
Cloos: Formatting

### ISSUE THREAD

**Issue by abrotman** [mrisher/smtp-sts#210]
There is one minor issue with tlsrpt-18:

If you look at:

https://www.ietf.org/rfcdiff?url2=draft-ietf-uta-smtp-tlsrpt-18

it is easy to see.  The formatting immediately before section 5 got squished.

On that html diff, search for the string:

    skipping to change at page 13, line 40

to see it.

**Comment by prbinu** [comment]
fixed
