### ISSUE TITLE
Policy record ABNF misses 'mx' field

### ISSUE THREAD

**Issue by aykevl** [mrisher/smtp-sts#228]
I see that the [-21 revision of the MTA-STS spec](https://tools.ietf.org/rfcdiff?url1=draft-ietf-uta-mta-sts-20.txt) removed the `sts-policy-mx` line from the `sts-policy-field` (and with that from the whole record). I'm assuming this is not intentional.

**Comment by danmarg** [comment]
Damn. Good catch. I'll check with how best to get this into the draft at the current stage. 

Thanks for that!

**Comment by danmarg** [comment]
https://github.com/mrisher/smtp-sts/pull/229

**Comment by danmarg** [comment]
Alexey says he already notified the RFC Editor about this issue. And that the above PR is wrong, so I should not merge it.
