### ISSUE TITLE
Reporting: Possible minor typo mistake in JSON example

### ISSUE THREAD

**Issue by XinyuYe** [mrisher/smtp-sts#231]
https://github.com/mrisher/smtp-sts/blob/23af47aec9fce424a356aa43e1ec50a063eacfc6/reporting.txt#L1724
In reporting Appendix B JSON Example (last line), we have an entry called failure-error-code but the entry isn't mentioned anywhere else.
In 4.4 Json schema we have an entry called failure-reason code 

https://github.com/mrisher/smtp-sts/blob/23af47aec9fce424a356aa43e1ec50a063eacfc6/reporting.txt#L649

**Comment by abrotman** [comment]
https://github.com/mrisher/smtp-sts/commit/bcf1d4319183243cda54778a9a222fe8ea978518#diff-9c2c31d060412097aef82d6255a5f07e

**Comment by abrotman** [comment]
Yes, it should have been "failure-reason-code", the commit above should resolve that.

**Comment by XinyuYe** [comment]
Thank you. I will close the PR too. By the way, do you also need to change the txt and xml version ? I don't know how these three versions work though.

**Comment by abrotman** [comment]
The document is with the RFC editors, we're to notify them directly.  The XML/TXT need to be regenerated.
