### ISSUE TITLE
TLSRPT1 - Discussion items

### ISSUE THREAD

**Issue by abrotman** [mrisher/smtp-sts#28]
Place holder for discussion 

Two items from me

1) I commented on this before, and I still think the lack of HELO in the report would make the report a bit less useful.  Any provider with a sizable infrastructure probably has everything going through a VIP or set of VIPs that are the same MX.  If I can't tell from the report which machine I actually talked to, it's going to make it much harder to isolate the issue.  Perhaps I"m reading: 

"receiving-mx-hostname": The hostname of the receiving MTA MX  record with which the sending MTA attempted to negotiate a      STARTTLS connection." 

In a different way than was intended.

2) I don't see any mention of delivering the report without requiring TLS for report delivery via SMTP, regardless of the receiving domain's STS policy.

**Comment by prbinu** [comment]
i think we should include this. We discussed this briefly during our M3AAWG meeting.

**Comment by mrisher** [comment]
Yeah, I like the HELO too. I thought we wanted to put it in the detailed ("forensic") report. Do you think it should go in the main one? If so, wouldn't it bloat considerably? 

I'll add the "without requiring TLS" caveat. We had that before.

**Comment by abrotman** [comment]
If you're only reporting issues, one would hope that your report isn't so bloated.  I mean, hopefully one doesn't have that many issues that the report is huge.

**Comment by abrotman** [comment]
This appears to be done in the current version.   I see a Report Delivery section, as well as HELO in the schema.  Objections to closing?

**Comment by prbinu** [comment]
👍

**Comment by mrisher** [comment]
fixed in current version.
