### ISSUE TITLE
TLSRPT HTTP MIME types

### ISSUE THREAD

**Issue by danmarg** [mrisher/smtp-sts#35]
We aren't very clear about the mime type for reporting POSTs (or should it be PUTs?). We probably should be.

**Comment by azet** [comment]
How about: https://www.iana.org/assignments/media-types/application/json

**Comment by eyeofthenico** [comment]
For reference, it is RFC4627 (https://tools.ietf.org/html/rfc4627).

**Comment by abrotman** [comment]
Resolved in the latest version
