### ISSUE TITLE
Editorial fixes for policy syntax

### ISSUE THREAD

**Issue by danmarg** [mrisher/smtp-sts#36]
The following issues were brought to my attention recently:

1. max-age vs policy_id: why are we inconsistent about underscores versus dashes?
2. The grammar for sts-version is missing a closing %22:
```
sts-version     = %x22 "version" %x22 *WSP %x3a *WSP  ; "version":
                  %x22 %x53 %x54 %x53 %x31            ; "STS1"
```

**Comment by mrisher** [comment]
you fixed this
