### ISSUE TITLE
Explain what happens when MX records differ

### ISSUE THREAD

**Issue by mrisher** [mrisher/smtp-sts#40]
From Scott@NIST: 1. Section 3 “mx”: pattern:  What is the sender to do when the mx: pattern in the MTA-STS policy differs from the MX set seen in the DNS? I would assume there would be some or complete overlap, but given enough time the sets may start to differ.

**Comment by mrisher** [comment]
accidentally omitted in v01. Assigning to v02 to resolve or dismiss.

**Comment by danmarg** [comment]
If the MX doesn't match that in the policy, it's invalid and you shouldn't deliver mail to it, no?

**Comment by abrotman** [comment]
Or is it just that the policy does not apply, and the sender does not perform validation to that MX (assuming others do match)?  What if none of the MXs match the mx: described in the policy?

**Comment by danmarg** [comment]
If the policy was never successfully applied, it is not valid (according to
the spec). If it is cached (i.e. has been applied successfully in the past)
and does not now match any of the MXes, of course you may be seeing MITM so
you must treat this as a policy failure.

**Comment by danmarg** [comment]
I believe I explained this better in the latest edits. Specifically: 

~~~
When applying a policy specifying `enforce` mode, sending MTAs SHOULD select
recipient MXs by first eliminating any MXs at lower priority than the current
host (if in the MX candidate set), then eliminating any non-matching (as
specified by the STS policy) MX hosts from the candidate MX set, and then
attempting delivery to matching hosts as indicated by their MX priority, until
delivery succeeds or the MX candidate set is empty.

If none of the attempted MX hosts validate according to the policy, the policy
MUST be refreshed at least once, as described in _Policy_ _Discovery_ _&_
_Authentication_, before a message should be permanently rejected.
~~~
