### ISSUE TITLE
Change §3.2.1 to explain expiration

### ISSUE THREAD

**Issue by mrisher** [mrisher/smtp-sts#41]
From Scott:
“Recipients should thus expect a policy will continue to be used by senders until both the HPTTS and TXT endpoints are updated and the ‘max_age’ value has passed.”

That max_age value is the longer value than the TTL so some senders will be using cached policies for a while until they either expire, or result in a validation failure when sending, but the former is probably more likely than the latter.

(Assigning to @danmarg , TTL expert ;)

**Comment by mrisher** [comment]
Wording change that was accidentally omitted from v01. Assigning to milestone v02.

**Comment by jjones425** [comment]
@danmarg does this still need to be updated?

**Comment by danmarg** [comment]
I'm not 100% sure I understand the comment. But I think the point is to really clarify two different situations:

1. Senders may use an old cached policy until max_age has passed. 
2. Senders may be unable to discover a new policy--even if the old policy does not validate--until the DNS TTL is updated. 

I think this could use some rewriting in the context of the state diagram. For now I'm just clarifying this section, however.

**Comment by danmarg** [comment]
https://github.com/mrisher/smtp-sts/pull/76
