### ISSUE TITLE
Incorrect ABNF character range for 'dtext'

### ISSUE THREAD

**Issue by lbaudoin** [mrisher/smtp-sts#42]
Currently 'dtext' is defined as:
dtext           =  %d30-39 /          ; 0-9
                   %d41-5A /          ; a-z
                   %61-7A /           ; A-Z
                   %2D                ; "-"

But the '0' is 0x30 in ASCII not 30 decimal, similarly 'a' is 0x41.
See https://tools.ietf.org/html/rfc5234 2.3 terminal values

So dtext should be specified as (note the %x):

dtext = %x30-39 /
            %x41-5A /
            %x61-7A /
            %x2D

**Comment by mrisher** [comment]
changed to the existing macros `(ALPHA / DIGIT / "-")`
