### ISSUE TITLE
Clarify or sync the MX field definition with RFC6125

### ISSUE THREAD

**Issue by lbaudoin** [mrisher/smtp-sts#50]
RFC6125 (https://tools.ietf.org/html/rfc6125#section-6.4.3) says that the leftmost part of the domain can contain a wildcard: 'baz*.example.net', '*baz.example.net' and 'b*z.example.net' are valid but section 3.1.2 of the STS spec only allows '*.example.net'.

Proposal: fix the ABNF to allow a wildcard anywhere in the leftmost part.

**Comment by mrisher** [comment]
updated to 
```
domain-match    = (*dtext 0*1("*") *dtext) *("." 1*dtext)
                                                          ; an optional wildcard
                                                          ; followed by a label
```

This does allow a single `*` in the rule, which is stupid but doesn't need to be invalid
