### ISSUE TITLE
Host policy on /.well-known/mta-sts.json

### ISSUE THREAD

**Issue by eyeofthenico** [mrisher/smtp-sts#59]
As STS policy is described in JSON format, I suggest we serve it with .json extension.
This will enable the correct content-type (application/json) as specified in RFC4627. 
The policy would be for instance hosted at https://example.com/.well-known/mta-sts.json instead of https://example.com/.well-known/mta-sts/current .

**Comment by mrisher** [comment]
SGTM.

**Comment by jjones425** [comment]
@mrisher @danmarg @prbinu @abrotman Thoughts on this issue?

**Comment by danmarg** [comment]
No strong opinion, but it seems fine to me. 

That said, I think Nico had separately suggested we host the policy on .well-known/$policy_id.json, i.e. use the policy ID from the TXT record, to make it easier to keep TXT version IDs in sync with the currently published policy. So should we do that instead, Nico?

**Comment by jjones425** [comment]
@eyeofthenico can you review this one and #62 to close these out?

**Comment by danmarg** [comment]
4aa8dfd
