### ISSUE TITLE
IETF 96 - need more info on TLS failures

### ISSUE THREAD

**Issue by jjones425** [mrisher/smtp-sts#66]
Viktor D: need more info on TLS failures

**Comment by jjones425** [comment]
Emailed Viktor to get more specific feedback

**Comment by jjones425** [comment]
Emailed Viktor again to get more feedback, if nothing received back by 8/5 will send out to the UTA mailing list to close on this issue.

**Comment by jjones425** [comment]
It is difficult to comment further without the context in which that comment was made.  Perhaps it was about what to do if one of the MX hosts fails authentication.  That is, clarifying the state-machine.

Or it might have been a comment about defining a few different failure modes, so that reporting can be more useful.

    * Failure to negotiate mutually acceptable TLS parameters.
    * Failure to construct a trusted chain.
    * Expired leaf certificate.
    * Untrusted certificate parameters (weak signature, weak
      public key).

Standardization of something more than "TLS failed", might well be quite useful.

Also, when/if in-band reporting is specified, it will be useful for the client to complete the handshake anyway, despite TLS authentication failure, so that the in-band notification can take place (over a possibly insecure TLS connection).

**Comment by jjones425** [comment]
@abrotman are you thinking of including this in the reporting spec? Just trying to close out on all other issues in the main STS spec.

**Comment by abrotman** [comment]
Based on Viktor's comments above, yes, this belongs to TLSRPT.

**Comment by abrotman** [comment]
Looked into this a bit more.

https://www.openssl.org/docs/manmaster/apps/verify.html

There are dozens of failure modes.  Do we want to enumerate them all? Classify/group them all? List a few, and then come up with a method to report the others that are not previously listed?

Such as, X509_V_ERR_UNNESTED_RESOURCE.  From the URL above, "RFC 3779 resource not subset of parent's resources."  This is all fine and dandy, but SSL libraries are going to continue to add different failure modes.  In the future, do we then alter this document, or create a method by which they can report the error more directly?

Side note, it could make sense to report the version of SSL/TLS libraries your MTA used when attempting the connection.  I'm not sure if that could lead to more problems than it solves, but it could aid with debugging.

**Comment by mrisher** [comment]
TLSRPT spec includes an optional `additional-info-uri` for specifying the details. I punted on what you'd actually put there, though, and am assuming it is human-readable free text. Does that satisfy?

**Comment by abrotman** [comment]
The way this was redone, I think this can be closed.
