### ISSUE TITLE
IETF 96 - mail reporting is underspecified

### ISSUE THREAD

**Issue by jjones425** [mrisher/smtp-sts#67]
J Levine: mail reporting is underspecified, is report in body, attachment? Also need way to permit report to third parties

**Comment by jjones425** [comment]
Define Reporting format like Attachment eg. DMARC compressed attachment

**Comment by prbinu** [comment]
example: https://tools.ietf.org/html/rfc7489#appendix-B.5

**Comment by mrisher** [comment]
fixed in branch `specify_reporting`
