### ISSUE TITLE
IETF 96 - HTTPS Policy timeout

### ISSUE THREAD

**Issue by jjones425** [mrisher/smtp-sts#69]
Recommended HTTPS Policy timeout
Keepalive etc 

T Hardie: deployment performance considerations are different in different situations, e.g. if you use http keepalive.

 Unlikely can come up with rules that work for everyone.

**Comment by mrisher** [comment]
Barry Leiba: if normal http usage doesn't match this use, could add more details re timeouts and such but don't do it if you don't need to

**Comment by jjones425** [comment]
I propose we close this one and revisit later if timeout is an issue after piloting. As Barry mentions, don't do it if you don't need to.

@danmarg @prbinu @mrisher @abrotman for comment

**Comment by danmarg** [comment]
In https://www.ietf.org/rfc/rfc2821.txt section 4.5.3.2 we have some stuff like:

>   Based on extensive experience with busy mail-relay hosts, the minimum
>    per-command timeout values SHOULD be as follows:
> 
>    Initial 220 Message: 5 minutes

These are _huge_ timeouts, far more generous than I would expect on an HTTPS GET. But one option is simply to parrot them: if RCPT can take 5 minutes, can a policy fetch also take 5 minutes?

**Comment by jjones425** [comment]
Do you think we even need to have this in the draft? If so, what section would it apply to?

**Comment by mrisher** [comment]
IIRC, someone jumped to our aid saying that, unless we have *different* requirements for timeouts there's no need to specify. I think it adds unnecessary clutter, but if someone wants it, I would copy-paste this in the block on ["Policy Discovery & Authentication"](https://github.com/mrisher/smtp-sts/blob/master/mta-sts.md#policy-discovery--authentication)

**Comment by danmarg** [comment]
I think if we say that this happens synchronously and fits into the 5
minute window I quoted, we need not specify anything else. If we say it
happens asynchronously, we do. It seems like for the sake of making
reasoning clearer we may want to specify the sync/async thing.

Somewhat aside from that, I am surprised that the timeout in the RFC is
really 5 minutes--I doubt that's the case in most implementations. With
such a high timeout, any *reasonable* bound on the HTTPS should not be a
big issue, IMO, yet I think (conversely) Viktor raised a (IMO valid)
concern about delivery queues backing up during slow policy fetch.

So the 5 minute thing strikes me as unlikely to be gospel. I can look at
our own MTA or ask Viktor about Postfix. But if the RFC 2821 timeouts are
misaligned with reality, maybe we shouldn't bother adding our own...

**Comment by danmarg** [comment]
If I'm reading our code right, we have not implemented those timeouts. Similarly, qmail has:

timeoutconnect	60	qmail-remote	how long, in seconds, to wait for SMTP connection
timeoutremote	1200	qmail-remote	how long, in seconds, to wait for remote server
timeoutsmtpd	1200	qmail-smtpd	how long, in seconds, to wait for SMTP client

Postfix has:

smtp_connect_timeout (default: 30s)

So my read on this is that nobody waits 5 minutes on the initial 220. Which somewhat makes me wonder about the utility of specifying timeouts in the RFC. Hmm.

**Comment by jjones425** [comment]
5 minutes does seem like a long time. How do we want to proceed? Should we update to align closer to Postfix?

**Comment by danmarg** [comment]
I'm not sure. I would say that given the lack of consistency between the RFC and implementations, having the RFC specify a timeout is of questionable value. 

I can email the UTA and SMTP mailing lists to get some feedback here. I'm far from an expert. But the desired parameters of an RFC-specified timeout that may be ignored in production deployments is not something I can easily reason about. ;)

**Comment by jjones425** [comment]
Thanks, let's go ahead and post this to the UTA list to get more feedback so we can update or not and close out.

**Comment by danmarg** [comment]
I've sent an email about this to UTA, but I will close this issue in the meantime in the name of bug bankruptcy. ;)
