### ISSUE TITLE
[UTA feedback] - Sections 2.x.x Updates

### ISSUE THREAD

**Issue by jjones425** [mrisher/smtp-sts#79]
From Stephen Farrell

- 2.1: I'm not sure if this is better included or not tbh.  I do think we want to say "TLSA also does this and in some ways better" but not sure if it's best done as pros and cons, which may generate more controversy than is worthwhile. I'd say best would be to start a thread on the WG list specifically about what this ought say about DANE/TLSA and see what consensus emerges. My bet is that after a bunch of discussion the WG might come to consensus on a fairly short paragraph or two that'd do the trick.

**Comment by jjones425** [comment]
From Viktor

> 2. Related Technologies
> 
> The DANE TLSA record [RFC7672] is similar, in that DANE is also designed to upgrade opportunistic encryption into required encryption.

Better:  ..., in that DANE is also designed to upgrade optional unauthenticated TLS to required authenticated TLS.

> DANE requires DNSSEC [RFC4033] for the secure delivery of policies; the mechanism described here presents a variant for systems not yet supporting DNSSEC.
> 
> 2.1. Differences from DANE
> 
> The primary difference between the mechanism described here and DANE is that DANE requires the use of DNSSEC to authenticate DANE TLSA records, whereas SMTP STS relies on the certificate authority (CA) system to avoid interception.

Partly redundant, given the above, also "to avoid interception" is too imprecise.
Just say that STS relies on CAs rather than DNSSEC to authenticate the published policy.

> (For a thorough discussion of this trade-off, see the section Security 
> Considerations.)
> 
> In addition, SMTP MTA-STS introduces a mechanism for failure reporting and a report-only mode, enabling offline ("report-only") deployments and auditing for compliance.

Since reporting is moving a separate document, that will also work with DANE, only "report-only" is now in scope.

> 
> 2.1.1. Advantages of SMTP MTA-STS when compared to DANE
> 
> SMTP MTA-STS offers the following advantages compared to DANE:
> 
> 	* Infrastructure: In comparison to DANE, this proposal does not require DNSSEC be deployed on either the sending or receiving domain. In addition, the reporting feature of SMTP MTA-STS can be deployed to perform offline analysis of STARTTLS failures, enabling mail providers to gain insight into the security of their SMTP connections without the need to modify MTA codebases directly.

The claim about not requiring MTA modifications is unsubstantiated, and I think false.
Clients need code changes to support either DANE or STS.  Servers don't need code changes to support either.  Since "report-only" is discussed in the next bullet the "In addition, ..."
text should be deleted.

> 	* Offline or report-only usage: DANE does not provide a reporting 
> mechanism and does not have a concept of "report-only" for failures;

The reporting draft will apply equally to DANE and STS, it is only the "report-only" mode that is (at present) not defined for DANE.

> as a result, a service provider cannot receive metrics on TLS 
> acceptability without asking senders to enforce a given policy;

This is not completely accurate, since a partial deployment is possible with DANE enabled on the primary MX, and not enabled on secondary MX hosts.  In that case, metrics from the primary MX host are generally adequate to guage interoperability, and the secondary MX hosts can be DANE-enabled once a sufficient comfort-level is achieved with the configuration of the primary.  DANE operators may not be aware of this option, but that's just a matter of publishing suitable "HOW-TO" documents, or even an informational RFC (though MTA administrators don't generally look for implementation guidance in RFCs).

> similarly, senders who cannot enforce DANE constraints at send-time have no mechanism to provide recipients such metrics from an offline (and potentially easier-to-deploy) logs-analysis batch process.

This part makes no sense.

> 2.1.2. Advantages of DANE when compared to SMTP MTA-STS
> 
> 	* Security: DANE offers an advantage against policy-lookup DoS attacks; that is, while a DNSSEC-signed NXDOMAIN response to a DANE lookup authoritatively indicates the lack of a DANE record, such an option to authenticate policy non-existence does not exist when looking up a policy over plain DNS.

More specifically, on "first-contact" DANE resists downgrade attacks, while STS does not.  Indeed STS does not resists attacks also when policy expires from the cache for destinations to which email is sent sufficiently infrequently.

Another important omission here is that when an MX-provider publishes TLSA records for an MX host, all customer DNSSEC-enabled domains that use that MX host are automatically secured.  The customers don't need to publish any policies at all.  The security policy is published by the MX provider.  Thus the majority of DANE-protected email domains (that I managed to find) are currently hosted by providers that host customer domains:

23317 transip.nl
 6135 udmedia.de
 1093 nederhost.net
  700 ec-elements.com
  663 bhosted.nl
  211 core-networks.de
  140 frobbit.se
  113 mailbox.org
  111 omc-mail.com
  ...

the customer domains just publish signed MX RRsets, for example:

   ; customer zone:
   mailous.com. IN MX 10 mx.transip.email.

   ; transip zone:
   mx.transip.email. IN A 149.210.149.76
   _25._tcp.mx.transip.email. IN TLSA 3 0 1 ee1b4c6e2fc82b542e456cea62452676c8049881e7feea8d2d7c7b0fccdc383f

[ If I can convince "one.com" to sign their zone and publish TLSA records for their MX hosts, there'll be at least another 500k new DANE domains, without any changes in the customer zones.  If anyone has good contacts at "one.com", please drop me a note. ]

**Comment by danmarg** [comment]
I've removed this section.
