### ISSUE TITLE
[UTA feedback] - Order of text consideration

### ISSUE THREAD

**Issue by jjones425** [mrisher/smtp-sts#91]
From Stephen Farrell

- order of text: If/when you've taken the above into account, I'd suggest an editing pass that considers the order in which things are presented in the draft. Right now, there's a lot of forward referencing that I think could be avoided by moving text about, and which'd lead to an easier read, that's more easily understood.

**Comment by danmarg** [comment]
I gave it another read-through and made some changes. Happy to close this if you are, Janet.

**Comment by danmarg** [comment]
Well, to be honest, there is still some forward-referencing, but I feel it's the best way to write this. Anyway, open to feedback.

**Comment by jjones425** [comment]
@danmarg did you include your changes in #95? It's hard to see where the changes were made.

**Comment by jjones425** [comment]
May make sense to validated once we have a clean version compiled.

**Comment by jjones425** [comment]
Addressed in upcoming version
