### ISSUE TITLE
[UTA feedback] - Section 1 Introduction updates

### ISSUE THREAD

**Issue by jjones425** [mrisher/smtp-sts#92]
From Viktor

> The STARTTLS extension to SMTP [RFC3207] allows SMTP clients and hosts to establish secure SMTP sessions over TLS. In its current form, however, it fails to provide (a) message confidentiality — because opportunistic STARTTLS is subject to downgrade attacks — and (b) server authenticity — because the trust relationship from email domain to MTA server identity is not cryptographically validated.

Replace: allows SMTP clients and hosts to establish secure SMTP sessions over TLS.
With:    allows SMTP clients and servers to negotiate the use of a TLS channel security.

The rest of the paragraph is not accurate as stated, and is redundant given the next paragraph, which is a better statement of the issues:

> While such opportunistic encryption protocols provide a high barrier against passive man-in-the-middle traffic interception, any attacker who can delete parts of the SMTP session (such as the "250 STARTTLS" response) or who can redirect the entire SMTP session (perhaps by overwriting the resolved MX record of the delivery domain) can perform such a downgrade or interception attack.

> This document defines a mechanism for recipient domains to publish policies specifying:

s/specifying/that specify/

> 	* whether MTAs sending mail to this domain can expect TLS support

Yes.

> 	* how MTAs can validate the TLS server certificate presented during 
> mail delivery

Left-over from the original that tried to mix STS with DANE I think, now obsolete, since authentication is always PKIX when used.

> 	* the expected identity of MXs that handle mail for this domain

Replace this with:

         * how to validate the names of the domain's MX hosts.

Should this still apply when the names are DNSSEC validated?  Or should clients that obtain DNSSEC "secure" MX RRsets (or denial of existence) skip the MX constraints in the STS policy, whose primary purpose is to harden STS against DNS reply forgery?

Allowing DNSSEC to handle DNS forgery when available, makes STS less fragile when the MX RRset legitimately differs from the published or cached STS policy.

> 	* what an implementing sender should do with messages when TLS cannot 
> be successfully negotiated

s/implementing sender/conforming client/

> The mechanism described is separated into four logical components:
> 
> 	• policy semantics: whether senders can expect a server for the 
> recipient domain to support TLS encryption and how to validate the TLS 
> certificate presented

See above, it seems to me that the "how to" is fixed.

> 	• failure report format: a mechanism for informing recipient domains 
> about aggregate failure statistics

This moves to a separate report format draft IIRC.

**Comment by danmarg** [comment]
https://github.com/mrisher/smtp-sts/pull/96
