### ISSUE TITLE
[UTA feedback]: Rename "_mta_sts" to "_mta-sts".

### ISSUE THREAD

**Issue by jjones425** [mrisher/smtp-sts#93]
From Viktor

> 3.2. Policy Expirations

s/Expirations/Expiration/

> An important consideration for domains publishing a policy is that senders will see a policy expiration as relative to the fetch of a policy cached by their recursive resolver.

This is rather poorly worded.  The policy expiration time is always measured from the time it is fetched via HTTPS, not from the retrieval of any DNS record.  Thus a policy will be used for up to its max-age.

The DNS TTL only comes into play when signaling a policy refresh via a new "id", in which case some clients may not notice the new "id" until the previous DNS TTL expires.

> Consequently, a sender MAY treat a policy as valid for up to {expiration time} + {DNS TTL}. Publishers SHOULD thus continue to expect senders to apply old policies for up to this duration.

This is wrong, no policy will be cached beyond the last time it was available via HTTPS + its max-age.  The DNS TTL is only of interest when policies are replaced, and makes it possible (barring DNS MiTM) for clients to notice that cached policies are stale, and thus refresh them sooner.

> 3.2.1. Policy Updates
> 
> Updating the policy requires that the owner make changes in two places: the _mta_sts RR record in the Policy Domain's DNS zone and at the corresponding HTTPS endpoint.

Please avoid internal "_" in DNS names.  Thus use "_mta-sts" instead.  See precedents with "_xmpp-server", "_xmpp-client", ...

> In the case where the HTTPS endpoint has been updated but the TXT record has not been, senders will not know there is a new policy released and may thus continue to use old, previously cached versions. Recipients should thus expect a policy will continue to be used by senders until both the HTTPS and TXT endpoints are updated and the TXT record's TTL has passed.

Here, consider describing the rollover process with multiple "id" values in the HTTPS policy record.

**Comment by danmarg** [comment]
https://github.com/mrisher/smtp-sts/pull/94

**Comment by danmarg** [comment]
Implemented with https://github.com/mrisher/smtp-sts/pull/95, but I'd like some feedback from other authors first.

**Comment by danmarg** [comment]
Done.
